feat: 1-я итерация ТЗ 14
heydancer/java-shareit pull request #2
Opened 2023-02-07 11:21 UTC by heydancer

2023-02-09 05:44 UTC, ErkinKasymaliev requested changes
привет, хорошая работа!
оставил комменты

2023-02-09 05:44 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +
тут разве не должен выставляться статус WAITING.

2023-02-09 11:44 UTC, heydancer commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +
поправил код, изначельно статус менялся в валидации. В методе валидации оставил только проверку.

2023-02-10 06:23 UTC, ErkinKasymaliev approved these changes
работа принята

2023-02-15 13:48 UTC, merged