feat: первая итерация ТЗ 15
heydancer/java-shareit pull request #3
Opened 2023-02-22 11:19 UTC by heydancer

2023-02-23 16:44 UTC, ErkinKasymaliev requested changes
привет, хорошая работа
оставил комменты

2023-02-23 16:44 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceTest.java
> +        assertTrue(itemDTO.getAvailable());
еще лучше проверить кол-во раз когда вызывался метод, например, здесь вы вызываете when(userRepository.findById(user.getId()))
                 .thenReturn(Optional.of(user));
         when(itemRepository.save(any(Item.class)))

и надо сделать следующее
verify(userRepository, times(2)).findById и verify(userRepository, times(2)).save . внутри times - то сколько раз должен был выщываться метод или verify(userRepository).save вызывался ли метод. Это относится ко всем методам где мокаете. И это рекомендательный коммент. Сделайте хотя в тестах контроллеров или сервисом, в одном из них

2023-02-26 12:09 UTC, heydancer commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceTest.java
> +        assertTrue(itemDTO.getAvailable());
Привет, добавил

2023-02-26 12:46 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-02-27 08:47 UTC, merged