Add docker
heydancer/java-shareit pull request #4
Opened 2023-03-01 21:58 UTC by heydancer

2023-03-02 06:06 UTC, ErkinKasymaliev requested changes
привет, отличная работа!
Оставил 1 коммент

2023-03-02 06:06 UTC, ErkinKasymaliev commented on server/pom.xml
> +            <groupId>org.springframework.boot</groupId>
тут это не нужно

2023-03-02 18:47 UTC, heydancer commented on server/pom.xml
> +            <groupId>org.springframework.boot</groupId>
Привет. Спасибо, исправил

2023-03-03 10:03 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-03-15 09:05 UTC, merged